name: flip3
channels:
  - defaults
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - biopython
  - pandas
  - pdoc3
  - pip
  - python>=3.10
  - pytorch
  - pytorch-cuda=11.8
  - numpy
  - torchaudio
  - torchvision
  - jupyter
  - tqdm
  - typeguard
  - pip:
      - fair-esm
      - -e .